// <auto-generated />
namespace FilmViewer.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Directory_refactoring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Directory_refactoring));
        
        string IMigrationMetadata.Id
        {
            get { return "201809241853479_Directory_refactoring"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
