//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmViewer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FilmViewer.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actor was edited succesfully.
        /// </summary>
        internal static string ActorEditedSuccesfully {
            get {
                return ResourceManager.GetString("ActorEditedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actor was removed succesfully.
        /// </summary>
        internal static string ActorRemovedSuccesfully {
            get {
                return ResourceManager.GetString("ActorRemovedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category was added.
        /// </summary>
        internal static string CategoryAdded {
            get {
                return ResourceManager.GetString("CategoryAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category with this name is already added..
        /// </summary>
        internal static string CategoryAlredyAdded {
            get {
                return ResourceManager.GetString("CategoryAlredyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category was edited succesfully.
        /// </summary>
        internal static string CategoryEdited {
            get {
                return ResourceManager.GetString("CategoryEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category was removed succesfully.
        /// </summary>
        internal static string CategoryRemovedSuccesfully {
            get {
                return ResourceManager.GetString("CategoryRemovedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director was edited succesfully.
        /// </summary>
        internal static string DirectorEditedSuccesfully {
            get {
                return ResourceManager.GetString("DirectorEditedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director was removed succesfully.
        /// </summary>
        internal static string DirectorRemovedSuccesfully {
            get {
                return ResourceManager.GetString("DirectorRemovedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login data.
        /// </summary>
        internal static string InvalidLoginData {
            get {
                return ResourceManager.GetString("InvalidLoginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main movie was added succesfully.
        /// </summary>
        internal static string MainMovieAddedSuccesfully {
            get {
                return ResourceManager.GetString("MainMovieAddedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main movie was removed succesfully.
        /// </summary>
        internal static string MainMovieRemovedSuccesfully {
            get {
                return ResourceManager.GetString("MainMovieRemovedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata with this name already exist.
        /// </summary>
        internal static string MetadataAlreadyExist {
            get {
                return ResourceManager.GetString("MetadataAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata created succesfully.
        /// </summary>
        internal static string MetadataCreatedMessage {
            get {
                return ResourceManager.GetString("MetadataCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata was deleted succesfully.
        /// </summary>
        internal static string MetadataDeleted {
            get {
                return ResourceManager.GetString("MetadataDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata was edited succesfully.
        /// </summary>
        internal static string MetadataEditedSuccesfully {
            get {
                return ResourceManager.GetString("MetadataEditedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie was edited succesfully.
        /// </summary>
        internal static string MovieEditedSuccesfully {
            get {
                return ResourceManager.GetString("MovieEditedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie was removed succesfully.
        /// </summary>
        internal static string MovieRemovedSuccesfully {
            get {
                return ResourceManager.GetString("MovieRemovedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed..
        /// </summary>
        internal static string PasswordChangedSuccesfully {
            get {
                return ResourceManager.GetString("PasswordChangedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roled added succesfully.
        /// </summary>
        internal static string RoleAddedToUser {
            get {
                return ResourceManager.GetString("RoleAddedToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rome removed from user succesfully.
        /// </summary>
        internal static string RoleRemovedFromUser {
            get {
                return ResourceManager.GetString("RoleRemovedFromUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occured.
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used is now locked.
        /// </summary>
        internal static string UserLocked {
            get {
                return ResourceManager.GetString("UserLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is now unlocked.
        /// </summary>
        internal static string UserUnlocked {
            get {
                return ResourceManager.GetString("UserUnlocked", resourceCulture);
            }
        }
    }
}
